import type { KnowledgeGraph } from "@/lib/knowledge-graph-types";

export function buildFixtureGraph(): KnowledgeGraph {
  return {
    nodes: [
      {
        id: "sample-answer-account-switch",
        label: "Account switch cleanup",
        type: "answer",
        text: "Cognee Graph Completion connects the account-switch cleanup answer to the source chunks that support it.",
        sourceApps: [],
        sourceEventIds: [],
        sourceUrl: "/intelligence",
        metadata: {
          kind: "graph_completion",
          searchType: "GRAPH_COMPLETION",
          datasetName: "corp-os-demo",
        },
        cognee: {
          source: "graph",
          kind: "graph_completion",
          searchType: "GRAPH_COMPLETION",
          datasetName: "corp-os-demo",
        },
      },
      {
        id: "sample-chunk-slack-account-switch",
        label: "Stale route report",
        type: "evidence",
        text: "Source event id: activity-slack-account-switch-001\nSource app: slack\nSource URL: /slack?channel=eng-platform&message=msg-account-switch-001\nActor: Maya Chen\nOccurred at: 2026-07-01T10:12:00Z\nContent:\nWe reproduced a privacy issue: after switching from one demo user to another, the previous user's selected conversation stayed open in the URL.",
        primarySourceApp: "slack",
        sourceApps: ["slack"],
        sourceEventIds: ["activity-slack-account-switch-001"],
        sourceUrl: "/slack?channel=eng-platform&message=msg-account-switch-001",
        metadata: {
          kind: "chunk",
          searchType: "CHUNKS",
          data_id: "sample-slack-data",
          chunk_id: "sample-slack-chunk",
          chunk_index: 0,
        },
        cognee: {
          source: "graph",
          kind: "chunk",
          searchType: "CHUNKS",
          datasetName: "corp-os-demo",
        },
      },
      {
        id: "sample-chunk-jira-account-switch",
        label: "Reset route state",
        type: "evidence",
        text: "Source event id: activity-jira-account-switch-002\nSource app: jira\nSource URL: /jira?project=CORP&view=board&issue=CORP-118\nContent:\nCORP-118 requires account switching to reset selected entity route state. No record from the old user may remain visible after switching users.",
        primarySourceApp: "jira",
        sourceApps: ["jira"],
        sourceEventIds: ["activity-jira-account-switch-002"],
        sourceUrl: "/jira?project=CORP&view=board&issue=CORP-118",
        metadata: {
          kind: "chunk",
          searchType: "CHUNKS",
          data_id: "sample-jira-data",
          chunk_id: "sample-jira-chunk",
          chunk_index: 0,
        },
        cognee: {
          source: "graph",
          kind: "chunk",
          searchType: "CHUNKS",
          datasetName: "corp-os-demo",
        },
      },
      {
        id: "sample-chunk-github-account-switch",
        label: "Clear query params",
        type: "evidence",
        text: "Source event id: activity-github-account-switch-003\nSource app: github\nSource URL: /github?repo=corp-os&tab=pulls&pr=42\nContent:\nPR 42 clears query parameters that point to user-scoped detail views when the active Corp OS user changes.",
        primarySourceApp: "github",
        sourceApps: ["github"],
        sourceEventIds: ["activity-github-account-switch-003"],
        sourceUrl: "/github?repo=corp-os&tab=pulls&pr=42",
        metadata: {
          kind: "chunk",
          searchType: "CHUNKS",
          data_id: "sample-github-data",
          chunk_id: "sample-github-chunk",
          chunk_index: 0,
        },
        cognee: {
          source: "graph",
          kind: "chunk",
          searchType: "CHUNKS",
          datasetName: "corp-os-demo",
        },
      },
      {
        id: "sample-chunk-confluence-account-switch",
        label: "Privacy boundary",
        type: "evidence",
        text: "Source event id: activity-confluence-account-switch-004\nSource app: confluence\nSource URL: /confluence?space=ENG&page=account-switch-privacy\nContent:\nDecision: account switching is a privacy boundary. Any user-scoped page state must be reset on switch.",
        primarySourceApp: "confluence",
        sourceApps: ["confluence"],
        sourceEventIds: ["activity-confluence-account-switch-004"],
        sourceUrl: "/confluence?space=ENG&page=account-switch-privacy",
        metadata: {
          kind: "chunk",
          searchType: "CHUNKS",
          data_id: "sample-confluence-data",
          chunk_id: "sample-confluence-chunk",
          chunk_index: 0,
        },
        cognee: {
          source: "graph",
          kind: "chunk",
          searchType: "CHUNKS",
          datasetName: "corp-os-demo",
        },
      },
    ],
    edges: [
      {
        id: "sample-edge-slack-answer",
        source: "sample-answer-account-switch",
        target: "sample-chunk-slack-account-switch",
        label: "supported by",
        type: "supported_by",
        sourceEventIds: ["activity-slack-account-switch-001"],
      },
      {
        id: "sample-edge-jira-answer",
        source: "sample-answer-account-switch",
        target: "sample-chunk-jira-account-switch",
        label: "supported by",
        type: "supported_by",
        sourceEventIds: ["activity-jira-account-switch-002"],
      },
      {
        id: "sample-edge-github-answer",
        source: "sample-answer-account-switch",
        target: "sample-chunk-github-account-switch",
        label: "supported by",
        type: "supported_by",
        sourceEventIds: ["activity-github-account-switch-003"],
      },
      {
        id: "sample-edge-confluence-answer",
        source: "sample-answer-account-switch",
        target: "sample-chunk-confluence-account-switch",
        label: "supported by",
        type: "supported_by",
        sourceEventIds: ["activity-confluence-account-switch-004"],
      },
    ],
    generatedAt: Date.now(),
    source: "fixture",
  };
}
