export type AppUser = {
  id: string;
  name: string;
  email: string;
  initials: string;
  color: string;
  role: "ADMIN" | "EMPLOYEE";
};

export const appUsers: AppUser[] = [
  {
    id: "marissa-cole",
    name: "Marissa Cole",
    email: "marissa.cole@redwoodinference.com",
    initials: "MC",
    color: "bg-stone-600 text-white",
    role: "ADMIN",
  },
  {
    id: "alex-chen",
    name: "Alex Chen",
    email: "alex-chen@redwoodinference.com",
    initials: "AC",
    color: "bg-violet-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "aisha-patel",
    name: "Aisha Patel",
    email: "aisha-patel@redwoodinference.com",
    initials: "AP",
    color: "bg-rose-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "arjun-patel",
    name: "Arjun Patel",
    email: "arjun-patel@redwoodinference.com",
    initials: "AP",
    color: "bg-violet-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "asha-patel",
    name: "Asha Patel",
    email: "asha-patel@redwoodinference.com",
    initials: "AP",
    color: "bg-pink-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "ava-chen",
    name: "Ava Chen",
    email: "ava.chen@redwoodinference.com",
    initials: "AC",
    color: "bg-amber-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "ava-martinez",
    name: "Ava Martinez",
    email: "ava-martinez@redwoodinference.com",
    initials: "AM",
    color: "bg-amber-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "avery-chen",
    name: "Avery Chen",
    email: "avery-chen@redwoodinference.com",
    initials: "AC",
    color: "bg-slate-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "ben-carter",
    name: "Ben Carter",
    email: "ben.carter@redwoodinference.com",
    initials: "BC",
    color: "bg-violet-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "diego-alvarez",
    name: "Diego Alvarez",
    email: "diego-alvarez@redwoodinference.com",
    initials: "DA",
    color: "bg-green-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "diego-martinez",
    name: "Diego Martinez",
    email: "diego-martinez@redwoodinference.com",
    initials: "DM",
    color: "bg-amber-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "diego-morales",
    name: "Diego Morales",
    email: "diego-morales@redwoodinference.com",
    initials: "DM",
    color: "bg-sky-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "ethan-park",
    name: "Ethan Park",
    email: "ethan.park@redwoodinference.com",
    initials: "EP",
    color: "bg-violet-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "hannah-schmitt",
    name: "Hannah Schmitt",
    email: "hannah.schmitt@redwoodinference.com",
    initials: "HS",
    color: "bg-amber-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "jonas-weber",
    name: "Jonas Weber",
    email: "jonas.weber@redwoodinference.com",
    initials: "JW",
    color: "bg-lime-700 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "jordan-blake",
    name: "Jordan Blake",
    email: "jordan.blake@redwoodinference.com",
    initials: "JB",
    color: "bg-pink-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "jordan-kim",
    name: "Jordan Kim",
    email: "jordan-kim@redwoodinference.com",
    initials: "JK",
    color: "bg-pink-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "jordan-lee",
    name: "Jordan Lee",
    email: "jordan.lee@redwoodinference.com",
    initials: "JL",
    color: "bg-cyan-700 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "jordan-patel",
    name: "Jordan Patel",
    email: "jordan-patel@redwoodinference.com",
    initials: "JP",
    color: "bg-lime-700 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "karthik-iyer",
    name: "Karthik Iyer",
    email: "karthik.iyer@redwoodinference.com",
    initials: "KI",
    color: "bg-orange-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "kevin-osei",
    name: "Kevin Osei",
    email: "kevin.osei@redwoodinference.com",
    initials: "KO",
    color: "bg-amber-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "kimberly-park",
    name: "Kimberly Park",
    email: "kimberly.park@redwoodinference.com",
    initials: "KP",
    color: "bg-purple-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "lauren-bishop",
    name: "Lauren Bishop",
    email: "lauren.bishop@redwoodinference.com",
    initials: "LB",
    color: "bg-lime-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "liam-chen",
    name: "Liam Chen",
    email: "liam-chen@redwoodinference.com",
    initials: "LC",
    color: "bg-sky-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "liam-o-connor",
    name: "Liam O'Connor",
    email: "liam-o-connor@redwoodinference.com",
    initials: "LO",
    color: "bg-fuchsia-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "marco-chen",
    name: "Marco Chen",
    email: "marco-chen@redwoodinference.com",
    initials: "MC",
    color: "bg-blue-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "marco-ruiz",
    name: "Marco Ruiz",
    email: "marco-ruiz@redwoodinference.com",
    initials: "MR",
    color: "bg-violet-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "marcus-chen",
    name: "Marcus Chen",
    email: "marcus-chen@redwoodinference.com",
    initials: "MC",
    color: "bg-stone-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "marcus-lin",
    name: "Marcus Lin",
    email: "marcus.lin@redwoodinference.com",
    initials: "ML",
    color: "bg-fuchsia-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "maria-chen",
    name: "Maria Chen",
    email: "maria-chen@redwoodinference.com",
    initials: "MC",
    color: "bg-amber-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "maria-cs",
    name: "Maria Cs",
    email: "maria-cs@redwoodinference.com",
    initials: "MC",
    color: "bg-rose-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "maria-g",
    name: "Maria G",
    email: "maria-g@redwoodinference.com",
    initials: "MG",
    color: "bg-orange-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "maria-support",
    name: "Maria Support",
    email: "maria-support@redwoodinference.com",
    initials: "MS",
    color: "bg-teal-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "maya-chen",
    name: "Maya Chen",
    email: "maya-chen@redwoodinference.com",
    initials: "MC",
    color: "bg-violet-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "maya-patel",
    name: "Maya Patel",
    email: "maya-patel@redwoodinference.com",
    initials: "MP",
    color: "bg-blue-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "maya-thompson",
    name: "Maya Thompson",
    email: "maya-thompson@redwoodinference.com",
    initials: "MT",
    color: "bg-gray-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "miguel-santos",
    name: "Miguel Santos",
    email: "miguel.santos@redwoodinference.com",
    initials: "MS",
    color: "bg-orange-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "monica-patel",
    name: "Monica Patel",
    email: "monica.patel@redwoodinference.com",
    initials: "MP",
    color: "bg-teal-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "priya-nair",
    name: "Priya Nair",
    email: "priya-nair@redwoodinference.com",
    initials: "PN",
    color: "bg-green-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "priya-natarajan",
    name: "Priya Natarajan",
    email: "priya.natarajan@redwoodinference.com",
    initials: "PN",
    color: "bg-orange-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "priya-shah",
    name: "Priya Shah",
    email: "priya.shah@redwoodinference.com",
    initials: "PS",
    color: "bg-stone-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "rachel-kim",
    name: "Rachel Kim",
    email: "rachel.kim@redwoodinference.com",
    initials: "RK",
    color: "bg-cyan-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "ravi-patel",
    name: "Ravi Patel",
    email: "ravi-patel@redwoodinference.com",
    initials: "RP",
    color: "bg-rose-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "rishi-malhotra",
    name: "Rishi Malhotra",
    email: "rishi.malhotra@redwoodinference.com",
    initials: "RM",
    color: "bg-orange-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "sean-gallagher",
    name: "Sean Gallagher",
    email: "sean.gallagher@redwoodinference.com",
    initials: "SG",
    color: "bg-rose-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "soojin-lee",
    name: "Soojin Lee",
    email: "soojin.lee@redwoodinference.com",
    initials: "SL",
    color: "bg-lime-700 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "vanessa-ortiz",
    name: "Vanessa Ortiz",
    email: "vanessa.ortiz@redwoodinference.com",
    initials: "VO",
    color: "bg-green-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "aisha",
    name: "Aisha",
    email: "aisha@redwoodinference.com",
    initials: "A",
    color: "bg-indigo-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "alice",
    name: "Alice",
    email: "alice@redwoodinference.com",
    initials: "A",
    color: "bg-green-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "ana",
    name: "Ana",
    email: "ana@redwoodinference.com",
    initials: "A",
    color: "bg-teal-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "anna",
    name: "Anna",
    email: "anna@redwoodinference.com",
    initials: "A",
    color: "bg-sky-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "anya",
    name: "Anya",
    email: "anya@redwoodinference.com",
    initials: "A",
    color: "bg-neutral-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "asha",
    name: "Asha",
    email: "asha@redwoodinference.com",
    initials: "A",
    color: "bg-cyan-700 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "ashley",
    name: "Ashley",
    email: "ashley@redwoodinference.com",
    initials: "A",
    color: "bg-stone-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "ava",
    name: "Ava",
    email: "ava@redwoodinference.com",
    initials: "A",
    color: "bg-purple-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "devon",
    name: "Devon",
    email: "devon@redwoodinference.com",
    initials: "D",
    color: "bg-yellow-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "elaine",
    name: "Elaine",
    email: "elaine@redwoodinference.com",
    initials: "E",
    color: "bg-teal-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "elena",
    name: "Elena",
    email: "elena@redwoodinference.com",
    initials: "E",
    color: "bg-rose-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "eli",
    name: "Eli",
    email: "eli@redwoodinference.com",
    initials: "E",
    color: "bg-purple-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "emily",
    name: "Emily",
    email: "emily@redwoodinference.com",
    initials: "E",
    color: "bg-zinc-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "emma",
    name: "Emma",
    email: "emma@redwoodinference.com",
    initials: "E",
    color: "bg-zinc-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "ivy",
    name: "Ivy",
    email: "ivy@redwoodinference.com",
    initials: "I",
    color: "bg-yellow-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "jamie",
    name: "Jamie",
    email: "jamie@redwoodinference.com",
    initials: "J",
    color: "bg-stone-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "jess",
    name: "Jess",
    email: "jess@redwoodinference.com",
    initials: "J",
    color: "bg-cyan-700 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "jordan",
    name: "Jordan",
    email: "jordan@redwoodinference.com",
    initials: "J",
    color: "bg-green-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "kai",
    name: "Kai",
    email: "kai@redwoodinference.com",
    initials: "K",
    color: "bg-lime-700 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "kevin",
    name: "Kevin",
    email: "kevin@redwoodinference.com",
    initials: "K",
    color: "bg-emerald-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "leah",
    name: "Leah",
    email: "leah@redwoodinference.com",
    initials: "L",
    color: "bg-slate-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "lena",
    name: "Lena",
    email: "lena@redwoodinference.com",
    initials: "L",
    color: "bg-slate-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "lina",
    name: "Lina",
    email: "lina@redwoodinference.com",
    initials: "L",
    color: "bg-indigo-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "marco",
    name: "Marco",
    email: "marco@redwoodinference.com",
    initials: "M",
    color: "bg-orange-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "maria",
    name: "Maria",
    email: "maria@redwoodinference.com",
    initials: "M",
    color: "bg-zinc-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "marie",
    name: "Marie",
    email: "marie@redwoodinference.com",
    initials: "M",
    color: "bg-orange-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "marta",
    name: "Marta",
    email: "marta@redwoodinference.com",
    initials: "M",
    color: "bg-cyan-700 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "maya",
    name: "Maya",
    email: "maya@redwoodinference.com",
    initials: "M",
    color: "bg-pink-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "mia",
    name: "Mia",
    email: "mia@redwoodinference.com",
    initials: "M",
    color: "bg-blue-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "mike",
    name: "Mike",
    email: "mike@redwoodinference.com",
    initials: "M",
    color: "bg-purple-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "mira",
    name: "Mira",
    email: "mira@redwoodinference.com",
    initials: "M",
    color: "bg-emerald-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "morgan",
    name: "Morgan",
    email: "morgan@redwoodinference.com",
    initials: "M",
    color: "bg-sky-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "nina",
    name: "Nina",
    email: "nina@redwoodinference.com",
    initials: "N",
    color: "bg-slate-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "noah",
    name: "Noah",
    email: "noah@redwoodinference.com",
    initials: "N",
    color: "bg-zinc-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "nora",
    name: "Nora",
    email: "nora@redwoodinference.com",
    initials: "N",
    color: "bg-indigo-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "oliver",
    name: "Oliver",
    email: "oliver@redwoodinference.com",
    initials: "O",
    color: "bg-fuchsia-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "olivia",
    name: "Olivia",
    email: "olivia@redwoodinference.com",
    initials: "O",
    color: "bg-indigo-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "priya",
    name: "Priya",
    email: "priya@redwoodinference.com",
    initials: "P",
    color: "bg-emerald-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "rachel",
    name: "Rachel",
    email: "rachel@redwoodinference.com",
    initials: "R",
    color: "bg-fuchsia-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "ravi",
    name: "Ravi",
    email: "ravi@redwoodinference.com",
    initials: "R",
    color: "bg-indigo-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "sam",
    name: "Sam",
    email: "sam@redwoodinference.com",
    initials: "S",
    color: "bg-gray-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "samir",
    name: "Samir",
    email: "samir@redwoodinference.com",
    initials: "S",
    color: "bg-purple-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "sara",
    name: "Sara",
    email: "sara@redwoodinference.com",
    initials: "S",
    color: "bg-fuchsia-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "sarah",
    name: "Sarah",
    email: "sarah@redwoodinference.com",
    initials: "S",
    color: "bg-emerald-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "sasha",
    name: "Sasha",
    email: "sasha@redwoodinference.com",
    initials: "S",
    color: "bg-indigo-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "sophia",
    name: "Sophia",
    email: "sophia@redwoodinference.com",
    initials: "S",
    color: "bg-slate-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "sophie",
    name: "Sophie",
    email: "sophie@redwoodinference.com",
    initials: "S",
    color: "bg-stone-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "tara",
    name: "Tara",
    email: "tara@redwoodinference.com",
    initials: "T",
    color: "bg-slate-600 text-white",
    role: "EMPLOYEE",
  },
  {
    id: "zoe",
    name: "Zoe",
    email: "zoe@redwoodinference.com",
    initials: "Z",
    color: "bg-stone-600 text-white",
    role: "EMPLOYEE",
  },
];

export function userToRecipient(user: AppUser) {
  return {
    name: user.name,
    email: user.email,
  };
}

export function getAppUserInitials(name: string) {
  return name
    .split(" ")
    .map((part) => part[0])
    .join("")
    .slice(0, 2)
    .toUpperCase();
}
